name: build and push image to docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Generate Date Tag
        id: date_tag
        run: |
          DATE_TAG=$(date +'%Y.%m.%d')
          echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV

        # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and push the Docker image with multiple tags
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .                    # The build context, usually the repository root
          push: true                    # Push the image after building
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/oomi-poller:latest
            ${{ secrets.DOCKER_USERNAME }}/oomi-poller:${{ env.DATE_TAG }}
