name: build and push image to docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t $DOCKER_USERNAME/oomi-poller:latest .
      - name: Login to Docker Hub
        run: echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Push image to Docker Hub
        run: docker push $DOCKER_USERNAME/oomi-poller:latest

